import { motion } from 'framer-motion';

export const Terms = () => {
  return (
    <div className="pt-32 pb-24 bg-[#030303] min-h-screen">
      <div className="max-w-4xl mx-auto px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="mb-12 border-b border-white/5 pb-12">
            <h1 className="text-4xl md:text-5xl font-black tracking-tighter mb-4 text-white">
              Terms of Service
            </h1>
            <p className="text-white/50 text-sm font-medium tracking-widest uppercase">
              Last Updated: October 24, 2024
            </p>
          </div>

          <div className="prose prose-invert prose-p:text-white/60 prose-headings:text-white max-w-none prose-a:text-purple-400">
            <p className="lead text-xl text-white/80">
              Welcome to TheDot Studio. These Terms of Service ("Terms") govern your use of our website, AI content creation platform, and associated services (collectively, the "Services"). By accessing or using our Services, you agree to be bound by these Terms.
            </p>

            <h2>1. Our Services</h2>
            <p>
              TheDot Studio provides automated AI content production pipelines, including but not limited to AI human cloning, voice synthesis, video editing, thumbnail generation, and multi-channel scaling strategy. Our services are categorized into distinct pricing tiers (Content Automate, Content Express, and Production Enterprise) as defined on our website.
            </p>

            <h2>2. User Content & Intellectual Property</h2>
            <p>
              When you upload text, audio, images, or video ("User Content") to our Services, you retain all ownership rights in your User Content. You grant us a limited, worldwide, non-exclusive, royalty-free license to use, reproduce, modify, and process your User Content solely to provide and improve the Services for you.
            </p>
            <p>
              The AI models, software, algorithms, and templates provided by TheDot Studio remain our exclusive intellectual property.
            </p>

            <h2>3. Generated Content & Commercial Rights</h2>
            <p>
              Upon successful payment of your subscription fees, you are granted full commercial rights to the videos, thumbnails, and audio generated by our AI engine on your behalf ("Generated Content"). You are solely responsible for ensuring that the Generated Content complies with the terms of service of any third-party platforms (e.g., YouTube, TikTok) where you distribute it.
            </p>

            <h2>4. AI Clones & Voice Models</h2>
            <p>
              If you utilize our Services to create a digital avatar or voice clone of a real person, you represent and warrant that you have explicit, documented consent from that individual to do so. TheDot Studio reserves the right to terminate accounts and delete models if we suspect unauthorized cloning.
            </p>

            <h2>5. Subscription, Billing, and Cancellation</h2>
            <p>
              Our Services are billed on a subscription basis (monthly or annually) based on your selected plan. Payments are non-refundable except as required by law. You may cancel your subscription at any time via your account dashboard; your access will continue until the end of your current billing cycle.
            </p>

            <h2>6. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, TheDot Studio shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising out of your use or inability to use the Services. While we optimize content for growth, we do not guarantee specific viewer counts, subscriber milestones, or revenue outcomes.
            </p>

            <h2>7. Contact Information</h2>
            <p>
              For legal inquiries regarding these Terms, please contact us at legal@thedotstudio.com.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
};
